### ISSUE TITLE
Multiple Streams using AioQuic 

### ISSUE THREAD

**Issue by devkdas** [pgjones/quart-trio#2]
hai ,

It is not an issue.
one small quick query

@pgjones 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code .

Sorry for raising an issue to ask this query.

Looking forward for your reply

Thank you.

**Comment by pgjones** [comment]
Sorry I missed this - it doesn't seem relevant to this project, do you mean with Hypercorn?

**Comment by devkdas** [comment]
hai @pgjones 

Thank you for replying back.

Sorry for asking this query here as this is unrelavent to any of the your projects.

No no, not about Hypercorn.I was asking about aioquic(https://github.com/aiortc/aioquic)

Looking for your reply.

Thank you.
@Karthikdasari0423

**Comment by pgjones** [comment]
I think you are asking in terms of client usage of aioquic, which I haven't done much (I mostly look at the server side). So I'd suggest asking on the aioquic repo.

**Comment by devkdas** [comment]
okay

yeah,there were multiple issues on this https://github.com/aiortc/aioquic/issues?q=is%3Aissue+is%3Aopen+streams+

so i was looking for help from contibutors to aioquic.

**Comment by pgjones** [comment]
ok, best to focus on those issues then.
