### ISSUE TITLE
Require Trio 0.22 and switch from deprecated MultiError to ExceptionGroup

### ISSUE THREAD

**Issue by Zac-HD** [pgjones/quart-trio#5]
Following https://github.com/python-trio/trio/pull/2213, Trio 0.22 was released and [`MultiError` is deprecated in favor of `(Base)ExceptionGroup`](https://trio.readthedocs.io/en/stable/reference-core.html#errors-in-multiple-child-tasks).

Updating to the latter is a pretty straightforward port, and avoids some deprecation warnings which can otherwise clutter up logs.

**Comment by pgjones** [comment]
Complete with #6.
